version: '2'
services:
  kanboard:
    build:
      .
    ports:
     - "2000:80"
     - "2001:443"
    environment:
     - KANBOARD_URL=http://leo-interop.prod.asteralabs.com/kanboard/
    volumes:
     - kanboard_data:/var/www/app/kanboard/data
     - kanboard_plugins:/var/www/app/kanboard/plugins
     - kanboard_ssl:/etc/nginx/ssl
volumes:
  kanboard_data:
    driver: local
  kanboard_plugins:
    driver: local
  kanboard_ssl:
    driver: local
